services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - pgdata_transactional:/var/lib/postgresql/data

volumes:
  # Transactional database to support the API.
  pgdata_transactional:
